---
title: "Diffusion image proccessing"
author: "Jeffrey T. Duda"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteIndexEntry{Diffusion weighted images}
    \usepackage[utf8]{inputenc}
---

```{r, echo = FALSE, message = FALSE, include = FALSE}
library( knitr )
knitr::opts_chunk$set(collapse = T, comment = "#>")
library(DANTsR)
library(kirby21.dti)

```

## Overview
This document provides some examples illustrating how [DANTsR](https://github.com/jeffduda/DANTsR)
may be used to work with diffusion weighted MR images.

```{r dwi2dti,message=FALSE,warnings=FALSE, fig.width=7, fig.height=5, echo=TRUE}

#download_dti_data()
grad = read.table(get_dti_info_filenames()[1]$fname[1])
dwi = antsImageRead(get_dti_filenames()[1])

mag = apply(as.matrix(grad), 1, function(x) sqrt( x[1]*x[1] + x[2]*x[2] + x[3]*x[3] ) )
b0Ids = which( mag == 0 )

grad=as.matrix(grad[1:33,])
bvalues = c(rep(1000,32),0)
grad = cbind(grad, bvalues)
grad[,3] = -grad[,3]

d = dim(dwi)
d[4] = 33
dwi = cropIndices(dwi, c(1,1,1,1), d)
dwi = dimensionToChannel(dwi)
dt = dtiReconstruction(dwi, grad, method="itk-svd")
fa = dtiAnisotropy(dt, method="fractionalanisotropy")
plot(fa)

tx = createAntsrTransform(dimension=3, type="Euler3DTransform", parameters=c(0,0,0.261799,20,-30,0))
dt2 = applyAntsrTransformToImage(tx, dt, fa)
invisible(applyAntsrTransformToPixels(tx, dt2, in.place=TRUE, pixel.as="diffusiontensor"))

#antsImageWrite(dt, "dt.nii.gz", as.tensor=TRUE )
#antsImageWrite(dt2, "dt2.nii.gz", as.tensor=TRUE )
#antsImageWrite(dt3, "dt3.nii.gz", as.tensor=TRUE )
```
